import { Product } from '@/types';

export const products: Product[] = [
  // Self-Lock Boxes
  {
    id: 'slb-001',
    name: 'Self-Lock Box - Small',
    category: 'boxes',
    subcategory: 'self-lock',
    images: ['/images/boxes/self-lock-small.jpg'],
    description: 'Durable self-lock boxes perfect for shipping and storage. Easy to assemble, no tape required.',
    dimensions: { length: 12, width: 10, height: 8 },
    gsm: [200, 250, 300],
    packSizes: [
      { size: 25, price: 450 },
      { size: 50, price: 850 },
      { size: 100, price: 1600 },
      { size: 1000, price: 15000 },
    ],
    basePrice: 18,
    inStock: true,
  },
  {
    id: 'slb-002',
    name: 'Self-Lock Box - Medium',
    category: 'boxes',
    subcategory: 'self-lock',
    images: ['/images/boxes/self-lock-medium.jpg'],
    description: 'Medium-sized self-lock boxes for various packaging needs.',
    dimensions: { length: 16, width: 12, height: 10 },
    gsm: [200, 250, 300],
    packSizes: [
      { size: 25, price: 550 },
      { size: 50, price: 1050 },
      { size: 100, price: 2000 },
      { size: 1000, price: 19000 },
    ],
    basePrice: 22,
    inStock: true,
  },
  {
    id: 'slb-003',
    name: 'Self-Lock Box - Large',
    category: 'boxes',
    subcategory: 'self-lock',
    images: ['/images/boxes/self-lock-large.jpg'],
    description: 'Large self-lock boxes for bulk packaging requirements.',
    dimensions: { length: 20, width: 16, height: 12 },
    gsm: [200, 250, 300],
    packSizes: [
      { size: 25, price: 700 },
      { size: 50, price: 1350 },
      { size: 100, price: 2600 },
      { size: 1000, price: 25000 },
    ],
    basePrice: 28,
    inStock: true,
  },
  // Corrugated Boxes
  {
    id: 'cb-001',
    name: 'Corrugated Box - Small',
    category: 'boxes',
    subcategory: 'corrugated',
    images: ['/images/boxes/corrugated-small.jpg'],
    description: 'Strong corrugated boxes with excellent protection for fragile items.',
    dimensions: { length: 10, width: 8, height: 6 },
    gsm: [200, 250, 300, 350],
    packSizes: [
      { size: 25, price: 400 },
      { size: 50, price: 750 },
      { size: 100, price: 1400 },
      { size: 1000, price: 13000 },
    ],
    basePrice: 16,
    inStock: true,
  },
  {
    id: 'cb-002',
    name: 'Corrugated Box - Medium',
    category: 'boxes',
    subcategory: 'corrugated',
    images: ['/images/boxes/corrugated-medium.jpg'],
    description: 'Medium corrugated boxes for standard shipping needs.',
    dimensions: { length: 14, width: 10, height: 8 },
    gsm: [200, 250, 300, 350],
    packSizes: [
      { size: 25, price: 500 },
      { size: 50, price: 950 },
      { size: 100, price: 1800 },
      { size: 1000, price: 17000 },
    ],
    basePrice: 20,
    inStock: true,
  },
  // Parcel Tapes
  {
    id: 'pt-001',
    name: 'Plain Parcel Tape',
    category: 'tapes',
    subcategory: 'plain',
    images: ['/images/tapes/plain-tape.jpg'],
    description: 'High-quality plain brown parcel tape for secure packaging.',
    thickness: '45 Microns',
    packSizes: [
      { size: 10, price: 250 },
      { size: 25, price: 600 },
      { size: 50, price: 1150 },
      { size: 100, price: 2200 },
      { size: 500, price: 10500 },
    ],
    basePrice: 25,
    inStock: true,
  },
  {
    id: 'pt-002',
    name: 'Amazon Parcel Tape',
    category: 'tapes',
    subcategory: 'amazon',
    images: ['/images/tapes/amazon-tape.jpg'],
    description: 'Amazon-branded parcel tape for FBA sellers.',
    thickness: '45 Microns',
    packSizes: [
      { size: 10, price: 280 },
      { size: 25, price: 650 },
      { size: 50, price: 1250 },
      { size: 100, price: 2400 },
      { size: 500, price: 11500 },
    ],
    basePrice: 28,
    inStock: true,
  },
  {
    id: 'pt-003',
    name: 'Flipkart Parcel Tape',
    category: 'tapes',
    subcategory: 'flipkart',
    images: ['/images/tapes/flipkart-tape.jpg'],
    description: 'Flipkart-branded parcel tape for sellers.',
    thickness: '45 Microns',
    packSizes: [
      { size: 10, price: 280 },
      { size: 25, price: 650 },
      { size: 50, price: 1250 },
      { size: 100, price: 2400 },
      { size: 500, price: 11500 },
    ],
    basePrice: 28,
    inStock: true,
  },
  {
    id: 'pt-004',
    name: 'White Parcel Tape',
    category: 'tapes',
    subcategory: 'white',
    images: ['/images/tapes/white-tape.jpg'],
    description: 'Premium white parcel tape for professional packaging.',
    thickness: '50 Microns',
    packSizes: [
      { size: 10, price: 300 },
      { size: 25, price: 700 },
      { size: 50, price: 1350 },
      { size: 100, price: 2600 },
      { size: 500, price: 12500 },
    ],
    basePrice: 30,
    inStock: true,
  },
  // Courier Covers
  {
    id: 'cc-001',
    name: 'Meesho Courier Cover',
    category: 'covers',
    subcategory: 'meesho',
    images: ['/images/covers/meesho-cover.jpg'],
    description: 'Meesho-branded courier covers with POD option.',
    thickness: '100 Microns',
    packSizes: [
      { size: 10, price: 150 },
      { size: 25, price: 350 },
      { size: 50, price: 650 },
      { size: 100, price: 1200 },
      { size: 500, price: 5500 },
    ],
    basePrice: 15,
    inStock: true,
  },
  {
    id: 'cc-002',
    name: 'Amazon Courier Cover',
    category: 'covers',
    subcategory: 'amazon',
    images: ['/images/covers/amazon-cover.jpg'],
    description: 'Amazon-branded courier covers for FBA shipments.',
    thickness: '100 Microns',
    packSizes: [
      { size: 10, price: 150 },
      { size: 25, price: 350 },
      { size: 50, price: 650 },
      { size: 100, price: 1200 },
      { size: 500, price: 5500 },
    ],
    basePrice: 15,
    inStock: true,
  },
  {
    id: 'cc-003',
    name: 'Flipkart Courier Cover',
    category: 'covers',
    subcategory: 'flipkart',
    images: ['/images/covers/flipkart-cover.jpg'],
    description: 'Flipkart-branded courier covers for sellers.',
    thickness: '100 Microns',
    packSizes: [
      { size: 10, price: 150 },
      { size: 25, price: 350 },
      { size: 50, price: 650 },
      { size: 100, price: 1200 },
      { size: 500, price: 5500 },
    ],
    basePrice: 15,
    inStock: true,
  },
  {
    id: 'cc-004',
    name: 'Myntra Courier Cover',
    category: 'covers',
    subcategory: 'myntra',
    images: ['/images/covers/myntra-cover.jpg'],
    description: 'Myntra-branded courier covers for fashion shipments.',
    thickness: '100 Microns',
    packSizes: [
      { size: 10, price: 150 },
      { size: 25, price: 350 },
      { size: 50, price: 650 },
      { size: 100, price: 1200 },
      { size: 500, price: 5500 },
    ],
    basePrice: 15,
    inStock: true,
  },
];

export const getProductById = (id: string): Product | undefined => {
  return products.find((p) => p.id === id);
};

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((p) => p.category === category);
};

export const getProductsBySubcategory = (subcategory: string): Product[] => {
  return products.filter((p) => p.subcategory === subcategory);
};

